In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
my_df = pd.read_csv('data/processed/AllEpitopeFeatures_larger.csv')

In [3]:
my_df

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage
0,E,MYSFVSEE,0,8,0.035578,0.002893,0.0,0
1,E,YSFVSEET,1,8,0.042296,0.003441,0.0,0
2,E,SFVSEETG,2,8,0.042296,0.003441,0.0,0
3,E,FVSEETGT,3,8,0.041116,0.003363,0.0,0
4,E,VSEETGTL,4,8,0.038914,0.003206,0.0,0
...,...,...,...,...,...,...,...,...
163791,S2,KGCCSCGSCCKFDEDDSEPVLKGVK,1244,25,0.116781,0.009853,0.0,0
163792,S2,GCCSCGSCCKFDEDDSEPVLKGVKL,1245,25,0.113617,0.009618,0.0,0
163793,S2,CCSCGSCCKFDEDDSEPVLKGVKLH,1246,25,0.113617,0.009618,0.0,0
163794,S2,CSCGSCCKFDEDDSEPVLKGVKLHY,1247,25,0.099336,0.008367,0.0,0
163795,S2,SCGSCCKFDEDDSEPVLKGVKLHYT,1248,25,0.098158,0.008289,0.0,0

In [4]:
my_df[my_df.protein=='S1']

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage
142423,S1,MFVFLVLL,0,8,0.157835,0.018689,0.0,0
142424,S1,FVFLVLLP,1,8,0.161367,0.018924,0.0,0
142425,S1,VFLVLLPL,2,8,0.159013,0.018768,0.0,0
142426,S1,FLVLLPLV,3,8,0.151556,0.018768,0.0,0
142427,S1,LVLLPLVS,4,8,0.194193,0.023381,0.0,0
...,...,...,...,...,...,...,...,...
163227,S1,PRRARSVASQSIIAYTMSLGAENSV,680,25,0.454565,0.057945,0.0,1
163228,S1,RRARSVASQSIIAYTMSLGAENSVA,681,25,0.220743,0.022834,0.0,1
163229,S1,RARSVASQSIIAYTMSLGAENSVAY,682,25,0.218389,0.022678,0.0,1
163230,S1,ARSVASQSIIAYTMSLGAENSVAYS,683,25,0.219566,0.022756,0.0,1
163231,S1,RSVASQSIIAYTMSLGAENSVAYSN,684,25,0.212026,0.022130,1.0,1

In [5]:
# my_df[my_df.protein=='S2']
# my_df[my_df.start_pos == 700]
my_df[np.logical_and(my_df.start_pos == 700, my_df.protein=='S2')]
# len(my_df)

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage
143123,S2,AENSVAYS,700,8,0.122984,0.014779,0.0,0
144389,S2,AENSVAYSN,700,9,0.124162,0.014858,1.0,0
145654,S2,AENSVAYSNN,700,10,0.124162,0.014858,1.0,0
146918,S2,AENSVAYSNNS,700,11,0.125340,0.014936,1.0,0
148181,S2,AENSVAYSNNSIA,700,13,0.126517,0.015014,1.0,0
149442,S2,AENSVAYSNNSIAI,700,14,0.127695,0.015092,1.0,0
150702,S2,AENSVAYSNNSIAIP,700,15,0.127695,0.015092,1.0,0
151961,S2,AENSVAYSNNSIAIPT,700,16,0.306343,0.042071,1.0,0
153219,S2,AENSVAYSNNSIAIPTN,700,17,0.308692,0.042227,1.0,0
154476,S2,AENSVAYSNNSIAIPTNF,700,18,0.308692,0.042227,1.0,0
155732,S2,AENSVAYSNNSIAIPTNFT,700,19,0.310121,0.042305,1.0,0
156987,S2,AENSVAYSNNSIAIPTNFTI,700,20,0.313273,0.042540,1.0,0
158241,S2,AENSVAYSNNSIAIPTNFTIS,700,21,0.316425,0.042774,1.0,0
159494,S2,AENSVAYSNNSIAIPTNFTISV,700,22,0.316425,0.042774,1.0,0
160746,S2,AENSVAYSNNSIAIPTNFTISVT,700,23,0.333157,0.044338,1.0,0
161997,S2,AENSVAYSNNSIAIPTNFTISVTT,700,24,0.334331,0.044417,1.0,0
163247,S2,AENSVAYSNNSIAIPTNFTISVTTE,700,25,0.334331,0.044417,1.0,0

### South African Mutation (501Y.V2)

In [6]:
### South African Mutation, add a column of binary values showing whether there is a mutation there
my_df['South_African_mutation'] = pd.Series(np.zeros(len(my_df)))

In [8]:
my_df

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage,South_African_mutation
0,E,MYSFVSEE,0,8,0.035578,0.002893,0.0,0,0.0
1,E,YSFVSEET,1,8,0.042296,0.003441,0.0,0,0.0
2,E,SFVSEETG,2,8,0.042296,0.003441,0.0,0,0.0
3,E,FVSEETGT,3,8,0.041116,0.003363,0.0,0,0.0
4,E,VSEETGTL,4,8,0.038914,0.003206,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...
163791,S2,KGCCSCGSCCKFDEDDSEPVLKGVK,1244,25,0.116781,0.009853,0.0,0,0.0
163792,S2,GCCSCGSCCKFDEDDSEPVLKGVKL,1245,25,0.113617,0.009618,0.0,0,0.0
163793,S2,CCSCGSCCKFDEDDSEPVLKGVKLH,1246,25,0.113617,0.009618,0.0,0,0.0
163794,S2,CSCGSCCKFDEDDSEPVLKGVKLHY,1247,25,0.099336,0.008367,0.0,0,0.0
163795,S2,SCGSCCKFDEDDSEPVLKGVKLHYT,1248,25,0.098158,0.008289,0.0,0,0.0

In [9]:
south_african_indeces = my_df[np.logical_or(my_df.protein=='S1', my_df.protein=='S2')].index

In [10]:
south_african_indeces

Int64Index([142423, 142424, 142425, 142426, 142427, 142428, 142429, 142430,
            142431, 142432,
            ...
            163786, 163787, 163788, 163789, 163790, 163791, 163792, 163793,
            163794, 163795],
           dtype='int64', length=21373)

In [12]:
def south_africa(mutation_point):
    '''
    Inputs:
        - mutation point: the number of the nucleotide in the S protein that is mutated
    Outputs:
        nothing
        But, it changes the my_df dataframe
    '''
    for my_index in south_african_indeces:
        temp_start = my_df.loc[my_index, 'start_pos']
        temp_len = my_df.loc[my_index, 'epi_len']
        if temp_start <= mutation_point and temp_start+temp_len > mutation_point:
            my_df.loc[my_index, 'South_African_mutation'] = 1
#             print(my_df.loc[my_index,:])

In [13]:
### From this paper: https://www.medrxiv.org/content/10.1101/2020.12.21.20248640v1.full.pdf
### Last figure graph B, remember everything here is 0-indexed, so 701 becomes 700
### A701V 
south_africa(700)
### D215G
south_africa(214)
### D80A
south_africa(79)
### E484K
south_africa(483)
### K417N
south_africa(416)
### L18F
south_africa(17)
### N501Y
south_africa(500)
### R246I
south_africa(245)

In [14]:

my_df

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage,South_African_mutation
0,E,MYSFVSEE,0,8,0.035578,0.002893,0.0,0,0.0
1,E,YSFVSEET,1,8,0.042296,0.003441,0.0,0,0.0
2,E,SFVSEETG,2,8,0.042296,0.003441,0.0,0,0.0
3,E,FVSEETGT,3,8,0.041116,0.003363,0.0,0,0.0
4,E,VSEETGTL,4,8,0.038914,0.003206,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...
163791,S2,KGCCSCGSCCKFDEDDSEPVLKGVK,1244,25,0.116781,0.009853,0.0,0,0.0
163792,S2,GCCSCGSCCKFDEDDSEPVLKGVKL,1245,25,0.113617,0.009618,0.0,0,0.0
163793,S2,CCSCGSCCKFDEDDSEPVLKGVKLH,1246,25,0.113617,0.009618,0.0,0,0.0
163794,S2,CSCGSCCKFDEDDSEPVLKGVKLHY,1247,25,0.099336,0.008367,0.0,0,0.0
163795,S2,SCGSCCKFDEDDSEPVLKGVKLHYT,1248,25,0.098158,0.008289,0.0,0,0.0

In [15]:
my_df.South_African_mutation.value_counts()

0.0    161580
1.0      2216
Name: South_African_mutation, dtype: int64

In [16]:
### Uncomment to save the file!!!
# my_df.to_csv('data/processed/AllEpitopeFeatures_with_South_African_mutation_larger.csv', index=False)

### UK mutation (B.1.1.7)

In [17]:
my_df = pd.read_csv('data/processed/AllEpitopeFeatures_with_South_African_mutation_larger.csv')

In [19]:
my_df;

In [20]:
my_df['UK_mutation'] = pd.Series(np.zeros(len(my_df)))

In [21]:
# my_df.UK_mutation.value_counts()
my_df.protein.unique();
my_df[my_df.protein=='ORF1a'];

In [22]:
my_df[np.logical_and(my_df.protein=='ORF1a', my_df.start_pos==1000)];

In [23]:
def uk_mutation(mutation_point, my_protein):
    '''
    Inputs:
        - mutation point: the number of the nucleotide in the S protein that is mutated
        - protein: the protein, ex. S (S1 and S2), ORF1a (there is no need to say ORF1ab as 
        there are no mutations past the cutoff between ORF1a and ORF1b) etc.
    Outputs:
        nothing
        But, it changes the my_df dataframe
    '''
    if my_protein == 'S':
        indeces = my_df[np.logical_or(my_df.protein=='S1', my_df.protein=='S2')].index
    else:
        indeces = my_df[my_df.protein==my_protein].index
        
    for my_index in indeces:
        temp_start = my_df.loc[my_index, 'start_pos']
        temp_len = my_df.loc[my_index, 'epi_len']
        if temp_start <= mutation_point and temp_start+temp_len > mutation_point:
            my_df.loc[my_index, 'UK_mutation'] = 1
#             print(my_index)
#             print(my_df.loc[my_index,:])

In [24]:
### From this paper: https://virological.org/t/preliminary-genomic-characterisation-of-an-emergent-sars-cov-2-lineage-in-the-uk-defined-by-a-novel-set-of-spike-mutations/563
### 0-indexed!!!, also instead of ORF1ab I use ORF1a, because all the mutations are in the beginning of 
### the ORF1ab, so in ORF1a

### ORF1ab -> ORF1a
### T1001I
uk_mutation(1000, 'ORF1a')
### A1708D
uk_mutation(1707, 'ORF1a')
### I2230T
uk_mutation(2229, 'ORF1a')
### SGF 3675-3677 deletion
uk_mutation(3674, 'ORF1a')
uk_mutation(3675, 'ORF1a')
uk_mutation(3676, 'ORF1a')

### S (Spike protein)
### HV 69-70 deletion
uk_mutation(68, 'S')
uk_mutation(69, 'S')
### Y144 deletion
uk_mutation(143, 'S')
### N501Y
uk_mutation(500, 'S')
### A570D
uk_mutation(569, 'S')
### P681H
uk_mutation(680, 'S')
### T716I
uk_mutation(715, 'S')
### S982A
uk_mutation(981, 'S')
### D1118H
uk_mutation(1117, 'S')

### ORF8
### Q27stop -> Basically get rid of all of ORF8 !!!!!

# ### R52I
# uk_mutation(51, 'ORF8')
# ### Y73C
# uk_mutation(72, 'ORF8')

### N
### D3L
uk_mutation(2, 'N')
### S235F
uk_mutation(234, 'N')

In [25]:
my_df.UK_mutation.value_counts()

0.0    159989
1.0      3807
Name: UK_mutation, dtype: int64

In [26]:
### Take care of all of ORF8
indeces_orf8 = my_df[my_df.protein=='ORF8'].index
indeces_orf8

Int64Index([139253, 139254, 139255, 139256, 139257, 139258, 139259, 139260,
            139261, 139262,
            ...
            141032, 141033, 141034, 141035, 141036, 141037, 141038, 141039,
            141040, 141041],
           dtype='int64', length=1789)

In [27]:
for my_index in indeces_orf8:
    my_df.loc[my_index, 'UK_mutation'] = 1

In [28]:
my_df.UK_mutation.value_counts()

0.0    158200
1.0      5596
Name: UK_mutation, dtype: int64

In [29]:
### Uncomment to save the file
# my_df.to_csv('data/processed/AllEpitopeFeatures_with_South_African_and_UK_mutation_larger.csv', index=False)

### Indian Mutation (B.1.617)

In [29]:
### Use paper: https://www.biorxiv.org/content/10.1101/2021.04.23.441101v1.full

In [136]:
my_df = pd.read_csv('data/processed/AllEpitopeFeatures_with_South_African_and_UK_mutation_larger.csv')

In [137]:
my_df

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage,South_African_mutation,UK_mutation
0,E,MYSFVSEE,0,8,0.035578,0.002893,0.0,0,0.0,0.0
1,E,YSFVSEET,1,8,0.042296,0.003441,0.0,0,0.0,0.0
2,E,SFVSEETG,2,8,0.042296,0.003441,0.0,0,0.0,0.0
3,E,FVSEETGT,3,8,0.041116,0.003363,0.0,0,0.0,0.0
4,E,VSEETGTL,4,8,0.038914,0.003206,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
163791,S2,KGCCSCGSCCKFDEDDSEPVLKGVK,1244,25,0.116781,0.009853,0.0,0,0.0,0.0
163792,S2,GCCSCGSCCKFDEDDSEPVLKGVKL,1245,25,0.113617,0.009618,0.0,0,0.0,0.0
163793,S2,CCSCGSCCKFDEDDSEPVLKGVKLH,1246,25,0.113617,0.009618,0.0,0,0.0,0.0
163794,S2,CSCGSCCKFDEDDSEPVLKGVKLHY,1247,25,0.099336,0.008367,0.0,0,0.0,0.0
163795,S2,SCGSCCKFDEDDSEPVLKGVKLHYT,1248,25,0.098158,0.008289,0.0,0,0.0,0.0

In [138]:
my_df['Indian_mutation'] = pd.Series(np.zeros(len(my_df)))

In [142]:
def indian_mutation(mutation_point, my_protein):
    '''
    Inputs:
        - mutation point: the number of the nucleotide in the S protein that is mutated
        - protein: the protein, ex. S (S1 and S2), ORF1a, ORF1b etc.
    Outputs:
        nothing
        But, it changes the my_df dataframe
    '''
#     if my_protein == 'S':
#         indeces = my_df[np.logical_or(my_df.protein=='S1', my_df.protein=='S2')].index
#     elif my_protein == '':
#         indeces = my_df[my_df.protein==my_protein].index

    indeces = my_df[my_df.protein==my_protein].index
    
    anything = False
        
    for my_index in indeces:
        temp_start = my_df.loc[my_index, 'start_pos']
        temp_len = my_df.loc[my_index, 'epi_len']
        if temp_start <= mutation_point and temp_start+temp_len > mutation_point:
            my_df.loc[my_index, 'Indian_mutation'] = 1
            anything = True
            
    if not anything:
        print('Problem with ', mutation_point, ' in protein ', my_protein)
#             print(my_index)
#             print(my_df.loc[my_index,:])

In [143]:
### Mutation points for the Indian Mutation (B.1.617)
### From the paper: https://www.biorxiv.org/content/10.1101/2021.04.23.441101v1.full
### For all the proteins the mutation point is -1 from what is written, because of zero indexing
### Exception: ORF1b, where the mutation point is -3 - 4399, because the numbering continues over from ORF1a
### Note that we need not worry in the same way about S2, as the numbering simply continues on there.

### ORF1a
### T 1567 I 
indian_mutation(1567 - 1, 'ORF1a')
### T 3646 A
indian_mutation(3646 - 1, 'ORF1a')

### ORF1b 
### P 4715 L
indian_mutation(4715 - 3 - 4399, 'ORF1b')
### G 5530 I
indian_mutation(5530 - 3 - 4399, 'ORF1b')
### M 5753 I
indian_mutation(5753 - 3 - 4399, 'ORF1b')
### K 6711 R
indian_mutation(6711 - 3 - 4399, 'ORF1b')
### S 6713 A
indian_mutation(6713 - 3 - 4399, 'ORF1b')

### S protein
### S1 domain
### T 95 I
indian_mutation(95 - 1, 'S1')
### G 142 D
indian_mutation(142 - 1, 'S1')
### E 154 K
indian_mutation(154 - 1, 'S1')
### L 452 R
indian_mutation(452 - 1, 'S1')
### E 484 Q
indian_mutation(484 - 1, 'S1')
### D 614 G
indian_mutation(614 - 1, 'S1')
### P 681 R
indian_mutation(681 - 1, 'S1')
### S2 domain
### Q 1071 H
indian_mutation(1071 - 1, 'S2')

### ORF3a
### S 26 L
indian_mutation(26 - 1, 'ORF3a')

### M
### I 82 S
indian_mutation(82 - 1, 'M')

### ORF6
### D 61 (the last amino acid)
indian_mutation(61 - 1, 'ORF6')
### 62 (anything after that)

### ORF7a
### N 43 Y
indian_mutation(43 - 1, 'ORF7a')
### V 82 A
indian_mutation(82 - 1, 'ORF7a')

### N
### R 203 M
indian_mutation(203 - 1, 'N')
### D 377 Y
indian_mutation(377 - 1, 'N')

In [145]:
my_df.Indian_mutation.value_counts()

0.0    158136
1.0      5660
Name: Indian_mutation, dtype: int64

In [147]:
### Code to save the data
# my_df.to_csv('data/processed/AllEpitopeFeatures_with_South_African_and_UK_and_Indian_mutation_larger.csv', index=False)

In [150]:
my_df[my_df.protein == 'ORF1a'].start_pos.unique()

array([   0,    1,    2, ..., 4390, 4391, 4392])

In [149]:
my_df[np.logical_and(my_df.protein == 'ORF1a', my_df.start_pos == 4392)]

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage,South_African_mutation,UK_mutation,Indian_mutation
16138,ORF1a,SADAQSFL,4392,8,0.018261,0.001408,0.0,0,0.0,0.0,0.0

In [151]:
my_df[my_df.protein == 'ORF1b'].start_pos.unique()

array([   0,    1,    2, ..., 2685, 2686, 2687])

In [152]:
my_df[my_df.protein == 'S1'].start_pos.unique()[-1]

684

In [153]:
my_df[my_df.protein == 'S2'].start_pos.unique()[0]

685

In [ ]:
### ORF1b is after ORF1a, but starts with 0
### S2 is after S1, but starts at 685, while S1 ends with 684

In [126]:
# my_df[np.logical_and(my_df.protein == 'ORF1b', my_df.start_pos == 4712 - 4399)]

In [125]:
# my_df[np.logical_and(my_df.protein == 'ORF1b', my_df.start_pos == 5529 - 4392)]

In [122]:
# my_df[np.logical_and(my_df.protein == 'N', my_df.start_pos == 376)]

In [123]:
# my_df.protein.unique()

In [124]:
# my_df[my_df.protein == 'ORF6']

In [44]:
# my_df[np.logical_and(my_df.protein == 'S1', my_df.start_pos == 245)]

In [60]:
# my_df[np.logical_and(my_df.protein == 'N', my_df.start_pos == 2)]

In [250]:
my_df[np.logical_and(my_df.protein == 'ORF1b', my_df.start_pos == 6713 - 3 - 4399)]

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage,South_African_mutation,UK_mutation,Indian_mutation,Brazilian_mutation
88589,ORF1b,SPFELEDF,2311,8,0.042578,0.003363,0.0,0,0.0,0.0,1.0,0.0
91277,ORF1b,SPFELEDFI,2311,9,0.046116,0.003597,0.0,0,0.0,0.0,1.0,0.0
93964,ORF1b,SPFELEDFIP,2311,10,0.053588,0.004145,0.0,0,0.0,0.0,1.0,0.0
96650,ORF1b,SPFELEDFIPM,2311,11,0.055946,0.004301,0.0,0,0.0,0.0,1.0,0.0
99335,ORF1b,SPFELEDFIPMDS,2311,13,0.066672,0.005083,0.0,0,0.0,0.0,1.0,0.0
102018,ORF1b,SPFELEDFIPMDST,2311,14,0.066672,0.005083,0.0,0,0.0,0.0,1.0,0.0
104700,ORF1b,SPFELEDFIPMDSTV,2311,15,0.066672,0.005083,0.0,0,0.0,0.0,1.0,0.0
107381,ORF1b,SPFELEDFIPMDSTVK,2311,16,0.067851,0.005161,0.0,0,0.0,0.0,1.0,0.0
110061,ORF1b,SPFELEDFIPMDSTVKN,2311,17,0.069030,0.005239,0.0,0,0.0,0.0,1.0,0.0
112740,ORF1b,SPFELEDFIPMDSTVKNY,2311,18,0.071232,0.005396,0.0,0,0.0,0.0,1.0,0.0
115418,ORF1b,SPFELEDFIPMDSTVKNYF,2311,19,0.071232,0.005396,0.0,0,0.0,0.0,1.0,0.0
118095,ORF1b,SPFELEDFIPMDSTVKNYFI,2311,20,0.073433,0.005552,0.0,0,0.0,0.0,1.0,0.0
120771,ORF1b,SPFELEDFIPMDSTVKNYFIT,2311,21,0.077836,0.005865,0.0,0,0.0,0.0,1.0,0.0
123446,ORF1b,SPFELEDFIPMDSTVKNYFITD,2311,22,0.083105,0.006256,0.0,0,0.0,0.0,1.0,0.0
126120,ORF1b,SPFELEDFIPMDSTVKNYFITDA,2311,23,0.086485,0.006490,0.0,0,0.0,0.0,1.0,0.0
128793,ORF1b,SPFELEDFIPMDSTVKNYFITDAQ,2311,24,0.086485,0.006490,0.0,0,0.0,0.0,1.0,0.0
131465,ORF1b,SPFELEDFIPMDSTVKNYFITDAQT,2311,25,0.090574,0.006803,0.0,0,0.0,0.0,1.0,0.0

### Brazilian Mutation (P.1)

In [194]:
### Use the following paper: https://virological.org/t/genomic-characterisation-of-an-emergent-sars-cov-2-lineage-in-manaus-preliminary-findings/586

In [195]:
my_df = pd.read_csv('data/processed/AllEpitopeFeatures_with_South_African_and_UK_and_Indian_mutation_larger.csv')

In [196]:
my_df.Indian_mutation.value_counts()

0.0    158136
1.0      5660
Name: Indian_mutation, dtype: int64

In [197]:
my_df['Brazilian_mutation'] = pd.Series(np.zeros(len(my_df)))

In [198]:
def brazilian_mutation(mutation_point, my_protein):
    ### exact same function as the indian_mutation !!!
    '''
    Inputs:
        - mutation point: the number of the nucleotide in the S protein that is mutated
        - protein: the protein, ex. S (S1 and S2), ORF1a, ORF1b etc.
    Outputs:
        nothing
        But, it changes the my_df dataframe
    '''
#     if my_protein == 'S':
#         indeces = my_df[np.logical_or(my_df.protein=='S1', my_df.protein=='S2')].index
#     elif my_protein == '':
#         indeces = my_df[my_df.protein==my_protein].index

    indeces = my_df[my_df.protein==my_protein].index
    
    anything = False
        
    for my_index in indeces:
        temp_start = my_df.loc[my_index, 'start_pos']
        temp_len = my_df.loc[my_index, 'epi_len']
        if temp_start <= mutation_point and temp_start+temp_len > mutation_point:
            my_df.loc[my_index, 'Brazilian_mutation'] = 1
            anything = True
            
    if not anything:
        print('Problem with ', mutation_point, ' in protein ', my_protein)
#             print(my_index)
#             print(my_df.loc[my_index,:])

In [199]:
### Mutations from the paper
### Paper: https://virological.org/t/genomic-characterisation-of-an-emergent-sars-cov-2-lineage-in-manaus-preliminary-findings/586

### For all the proteins the mutation point is -1 from what is written, because of zero indexing
### Exception: ORF1b, where the mutation point is -3 - 4399, because the numbering continues over from ORF1a
### Note that we need not worry in the same way about S2, as the numbering simply continues on there.



### ORF1ab
### ORF1a
### S 1188 L
brazilian_mutation(1188 - 1, 'ORF1a')
### K 1795 Q
brazilian_mutation(1795 - 1, 'ORF1a')
### del 3675
brazilian_mutation(3675 - 1, 'ORF1a')
### del 3676
brazilian_mutation(3676 - 1, 'ORF1a')
### del 3677
brazilian_mutation(3677 - 1, 'ORF1a')
### ORF1b
### E 5665 D
brazilian_mutation(5665 - 3 - 4399, 'ORF1b')

### S (S1 and S2)
### S1
### L 18 F
brazilian_mutation(18 - 1, 'S1')
### T 20 N
brazilian_mutation(20 - 1, 'S1')
### P 26 S
brazilian_mutation(26 - 1, 'S1')
### D 138 Y
brazilian_mutation(138 - 1, 'S1')
### R 190 S
brazilian_mutation(190 - 1, 'S1')
### K 417 T (important!!!)
brazilian_mutation(417 - 1, 'S1')
### E 484 K (important!!!)
brazilian_mutation(484 - 1, 'S1')
### N 501 Y (important!!!)
brazilian_mutation(501 - 1, 'S1')
### H 655 Y
brazilian_mutation(655 - 1, 'S1')
### S2
### T 1027 I
brazilian_mutation(1027 - 1, 'S2')

### ORF8
### E 92 K
brazilian_mutation(92 - 1, 'ORF8')
### insertion in DNA 28269 - 28273 ???

### N
### P 80 R
brazilian_mutation(80 - 1, 'N')

In [200]:
### Checking that things work
# my_df[np.logical_and(my_df.protein == 'ORF1b', my_df.start_pos == 5665 - 3 - 4399)]

In [201]:
# my_df[np.logical_and(my_df.protein == 'N', my_df.start_pos == 79)]

In [202]:
my_df.Brazilian_mutation.value_counts()

0.0    159700
1.0      4096
Name: Brazilian_mutation, dtype: int64

In [251]:
my_df[np.logical_and(my_df.protein == 'N', my_df.start_pos == 80 - 1)]

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage,South_African_mutation,UK_mutation,Indian_mutation,Brazilian_mutation
4592,N,PDDQIGYY,79,8,0.030754,0.002581,0.0,0,0.0,0.0,0.0,1.0
5004,N,PDDQIGYYR,79,9,0.030754,0.002581,0.0,0,0.0,0.0,0.0,1.0
5415,N,PDDQIGYYRR,79,10,0.031933,0.002659,0.0,0,0.0,0.0,0.0,1.0
5825,N,PDDQIGYYRRA,79,11,0.039191,0.003206,0.0,0,0.0,0.0,0.0,1.0
6234,N,PDDQIGYYRRATR,79,13,0.039191,0.003206,0.0,0,0.0,0.0,0.0,1.0
6641,N,PDDQIGYYRRATRR,79,14,0.039191,0.003206,0.0,0,0.0,0.0,0.0,1.0
7047,N,PDDQIGYYRRATRRI,79,15,0.039191,0.003206,0.0,0,0.0,0.0,0.0,1.0
7452,N,PDDQIGYYRRATRRIR,79,16,0.040370,0.003284,0.0,0,0.0,0.0,0.0,1.0
7856,N,PDDQIGYYRRATRRIRG,79,17,0.042728,0.003441,0.0,0,0.0,0.0,0.0,1.0
8259,N,PDDQIGYYRRATRRIRGG,79,18,0.042728,0.003441,0.0,0,0.0,0.0,0.0,1.0
8661,N,PDDQIGYYRRATRRIRGGD,79,19,0.042728,0.003441,0.0,0,0.0,0.0,0.0,1.0
9062,N,PDDQIGYYRRATRRIRGGDG,79,20,0.042728,0.003441,0.0,0,0.0,0.0,0.0,1.0
9462,N,PDDQIGYYRRATRRIRGGDGK,79,21,0.042728,0.003441,0.0,0,0.0,0.0,0.0,1.0
9861,N,PDDQIGYYRRATRRIRGGDGKM,79,22,0.044930,0.003597,0.0,0,0.0,0.0,0.0,1.0
10259,N,PDDQIGYYRRATRRIRGGDGKMK,79,23,0.044930,0.003597,0.0,0,0.0,0.0,0.0,1.0
10656,N,PDDQIGYYRRATRRIRGGDGKMKD,79,24,0.077581,0.006647,0.0,0,0.0,0.0,0.0,1.0
11052,N,PDDQIGYYRRATRRIRGGDGKMKDL,79,25,0.077581,0.006647,0.0,0,0.0,0.0,0.0,1.0

In [253]:
### Code to save the data
### my_df.to_csv('data/processed/AllEpitopeFeatures_with_South_African_and_UK_and_Indian_and_Brazilian_mutation_larger.csv', index=False)

### Play around with the total data

In [254]:
my_df = pd.read_csv('data/processed/AllEpitopeFeatures_with_South_African_and_UK_and_Indian_and_Brazilian_mutation_larger.csv')

In [257]:
my_df.Brazilian_mutation.value_counts()

0.0    159700
1.0      4096
Name: Brazilian_mutation, dtype: int64

### Set the mutation rate equal to 1 if the peptide is hit by (South_African, UK, Indian, Brazilian) mutation

In [258]:
my_df = pd.read_csv('data/processed/AllEpitopeFeatures_with_South_African_and_UK_and_Indian_and_Brazilian_mutation_larger.csv')

In [259]:
my_df

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage,South_African_mutation,UK_mutation,Indian_mutation,Brazilian_mutation
0,E,MYSFVSEE,0,8,0.035578,0.002893,0.0,0,0.0,0.0,0.0,0.0
1,E,YSFVSEET,1,8,0.042296,0.003441,0.0,0,0.0,0.0,0.0,0.0
2,E,SFVSEETG,2,8,0.042296,0.003441,0.0,0,0.0,0.0,0.0,0.0
3,E,FVSEETGT,3,8,0.041116,0.003363,0.0,0,0.0,0.0,0.0,0.0
4,E,VSEETGTL,4,8,0.038914,0.003206,0.0,0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
163791,S2,KGCCSCGSCCKFDEDDSEPVLKGVK,1244,25,0.116781,0.009853,0.0,0,0.0,0.0,0.0,0.0
163792,S2,GCCSCGSCCKFDEDDSEPVLKGVKL,1245,25,0.113617,0.009618,0.0,0,0.0,0.0,0.0,0.0
163793,S2,CCSCGSCCKFDEDDSEPVLKGVKLH,1246,25,0.113617,0.009618,0.0,0,0.0,0.0,0.0,0.0
163794,S2,CSCGSCCKFDEDDSEPVLKGVKLHY,1247,25,0.099336,0.008367,0.0,0,0.0,0.0,0.0,0.0
163795,S2,SCGSCCKFDEDDSEPVLKGVKLHYT,1248,25,0.098158,0.008289,0.0,0,0.0,0.0,0.0,0.0

In [260]:
for ind in my_df.index:
    if ind%10000==0:
        print(ind)
    if my_df.loc[ind,'UK_mutation'] == 1 or my_df.loc[ind,'South_African_mutation'] == 1 or my_df.loc[ind,'Indian_mutation'] == 1 or my_df.loc[ind,'Brazilian_mutation'] == 1:
        my_df.loc[ind,'perc_mutated'] = 1.0

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000

In [261]:
new_df = my_df.drop(labels = ['South_African_mutation','UK_mutation', 'Indian_mutation', 'Brazilian_mutation'], axis='columns')

In [262]:
new_df

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage
0,E,MYSFVSEE,0,8,0.035578,0.002893,0.0,0
1,E,YSFVSEET,1,8,0.042296,0.003441,0.0,0
2,E,SFVSEETG,2,8,0.042296,0.003441,0.0,0
3,E,FVSEETGT,3,8,0.041116,0.003363,0.0,0
4,E,VSEETGTL,4,8,0.038914,0.003206,0.0,0
...,...,...,...,...,...,...,...,...
163791,S2,KGCCSCGSCCKFDEDDSEPVLKGVK,1244,25,0.116781,0.009853,0.0,0
163792,S2,GCCSCGSCCKFDEDDSEPVLKGVKL,1245,25,0.113617,0.009618,0.0,0
163793,S2,CCSCGSCCKFDEDDSEPVLKGVKLH,1246,25,0.113617,0.009618,0.0,0
163794,S2,CSCGSCCKFDEDDSEPVLKGVKLHY,1247,25,0.099336,0.008367,0.0,0
163795,S2,SCGSCCKFDEDDSEPVLKGVKLHYT,1248,25,0.098158,0.008289,0.0,0

In [264]:
### Code to save the new data!!!
### new_df.to_csv('data/processed/AllEpitopeFeatures_accounting_for_all_major_mutations_mutrate_set_to_1.csv')

In [265]:
new_df[np.logical_and(new_df.protein == 'S1', new_df.start_pos == 451)]

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage
142874,S1,LYRLFRKS,451,8,0.111980,1.0,0.0,0
144140,S1,LYRLFRKSN,451,9,0.111980,1.0,0.0,0
145405,S1,LYRLFRKSNL,451,10,0.111980,1.0,0.0,0
146669,S1,LYRLFRKSNLK,451,11,0.113158,1.0,0.0,0
147932,S1,LYRLFRKSNLKPF,451,13,0.114336,1.0,0.0,0
149193,S1,LYRLFRKSNLKPFE,451,14,0.114336,1.0,0.0,0
150453,S1,LYRLFRKSNLKPFER,451,15,0.114336,1.0,0.0,0
151712,S1,LYRLFRKSNLKPFERD,451,16,0.114336,1.0,0.0,0
152970,S1,LYRLFRKSNLKPFERDI,451,17,0.116537,1.0,0.0,0
154227,S1,LYRLFRKSNLKPFERDIS,451,18,0.116537,1.0,0.0,0
155483,S1,LYRLFRKSNLKPFERDIST,451,19,0.120624,1.0,0.0,0
156738,S1,LYRLFRKSNLKPFERDISTE,451,20,0.121802,1.0,0.0,0
157992,S1,LYRLFRKSNLKPFERDISTEI,451,21,0.121802,1.0,0.0,0
159245,S1,LYRLFRKSNLKPFERDISTEIY,451,22,0.121802,1.0,0.0,0
160497,S1,LYRLFRKSNLKPFERDISTEIYQ,451,23,0.121802,1.0,0.0,0
161748,S1,LYRLFRKSNLKPFERDISTEIYQA,451,24,0.122980,1.0,0.0,0
162998,S1,LYRLFRKSNLKPFERDISTEIYQAG,451,25,0.125337,1.0,0.0,0

## New code for setting the mutation rate for any peptide that has the UK or South African Mutation equal to 1 (can run this separately from the above)

In [15]:
my_df = pd.read_csv('data/processed/AllEpitopeFeatures_with_South_African_and_UK_mutation_larger.csv')

In [16]:
my_df

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage,South_African_mutation,UK_mutation
0,E,MYSFVSEE,0,8,0.035578,0.002893,0.0,0,0.0,0.0
1,E,YSFVSEET,1,8,0.042296,0.003441,0.0,0,0.0,0.0
2,E,SFVSEETG,2,8,0.042296,0.003441,0.0,0,0.0,0.0
3,E,FVSEETGT,3,8,0.041116,0.003363,0.0,0,0.0,0.0
4,E,VSEETGTL,4,8,0.038914,0.003206,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
163791,S2,KGCCSCGSCCKFDEDDSEPVLKGVK,1244,25,0.116781,0.009853,0.0,0,0.0,0.0
163792,S2,GCCSCGSCCKFDEDDSEPVLKGVKL,1245,25,0.113617,0.009618,0.0,0,0.0,0.0
163793,S2,CCSCGSCCKFDEDDSEPVLKGVKLH,1246,25,0.113617,0.009618,0.0,0,0.0,0.0
163794,S2,CSCGSCCKFDEDDSEPVLKGVKLHY,1247,25,0.099336,0.008367,0.0,0,0.0,0.0
163795,S2,SCGSCCKFDEDDSEPVLKGVKLHYT,1248,25,0.098158,0.008289,0.0,0,0.0,0.0

In [14]:
for ind in my_df.index:
    if ind%10000==0:
        print(ind)
    if my_df.loc[ind,'UK_mutation'] == 1 or my_df.loc[ind,'South_African_mutation'] == 1:
        my_df.loc[ind,'perc_mutated'] = 1.0

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000

In [15]:
my_df

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage,South_African_mutation,UK_mutation
0,E,MYSFVSEE,0,8,0.035578,0.002893,0.0,0,0.0,0.0
1,E,YSFVSEET,1,8,0.042296,0.003441,0.0,0,0.0,0.0
2,E,SFVSEETG,2,8,0.042296,0.003441,0.0,0,0.0,0.0
3,E,FVSEETGT,3,8,0.041116,0.003363,0.0,0,0.0,0.0
4,E,VSEETGTL,4,8,0.038914,0.003206,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
163791,S2,KGCCSCGSCCKFDEDDSEPVLKGVK,1244,25,0.116781,0.009853,0.0,0,0.0,0.0
163792,S2,GCCSCGSCCKFDEDDSEPVLKGVKL,1245,25,0.113617,0.009618,0.0,0,0.0,0.0
163793,S2,CCSCGSCCKFDEDDSEPVLKGVKLH,1246,25,0.113617,0.009618,0.0,0,0.0,0.0
163794,S2,CSCGSCCKFDEDDSEPVLKGVKLHY,1247,25,0.099336,0.008367,0.0,0,0.0,0.0
163795,S2,SCGSCCKFDEDDSEPVLKGVKLHYT,1248,25,0.098158,0.008289,0.0,0,0.0,0.0

In [17]:
my_df[my_df.UK_mutation == 1]
my_df[my_df.South_African_mutation == 1]

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage,South_African_mutation,UK_mutation
142433,S1,VSSQCVNL,10,8,0.208723,1.0,1.0,0,1.0,0.0
142434,S1,SSQCVNLT,11,8,0.209743,1.0,1.0,0,1.0,0.0
142435,S1,SQCVNLTT,12,8,0.198939,1.0,1.0,0,1.0,0.0
142436,S1,QCVNLTTR,13,8,0.211701,1.0,1.0,0,1.0,0.0
142437,S1,CVNLTTRT,14,8,0.228375,1.0,1.0,0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
163243,S2,MSLGAENSVAYSNNSIAIPTNFTIS,696,25,0.321672,1.0,1.0,0,1.0,1.0
163244,S2,SLGAENSVAYSNNSIAIPTNFTISV,697,25,0.321672,1.0,1.0,0,1.0,1.0
163245,S2,LGAENSVAYSNNSIAIPTNFTISVT,698,25,0.334331,1.0,1.0,0,1.0,1.0
163246,S2,GAENSVAYSNNSIAIPTNFTISVTT,699,25,0.334331,1.0,1.0,0,1.0,1.0
163247,S2,AENSVAYSNNSIAIPTNFTISVTTE,700,25,0.334331,1.0,1.0,0,1.0,1.0

In [18]:
new_df = my_df.drop(labels = ['South_African_mutation','UK_mutation'], axis='columns')

In [19]:
new_df

,protein,epitope,start_pos,epi_len,entropy,perc_mutated,glyco_probs,crosses_cleavage
0,E,MYSFVSEE,0,8,0.035578,0.002893,0.0,0
1,E,YSFVSEET,1,8,0.042296,0.003441,0.0,0
2,E,SFVSEETG,2,8,0.042296,0.003441,0.0,0
3,E,FVSEETGT,3,8,0.041116,0.003363,0.0,0
4,E,VSEETGTL,4,8,0.038914,0.003206,0.0,0
...,...,...,...,...,...,...,...,...
163791,S2,KGCCSCGSCCKFDEDDSEPVLKGVK,1244,25,0.116781,0.009853,0.0,0
163792,S2,GCCSCGSCCKFDEDDSEPVLKGVKL,1245,25,0.113617,0.009618,0.0,0
163793,S2,CCSCGSCCKFDEDDSEPVLKGVKLH,1246,25,0.113617,0.009618,0.0,0
163794,S2,CSCGSCCKFDEDDSEPVLKGVKLHY,1247,25,0.099336,0.008367,0.0,0
163795,S2,SCGSCCKFDEDDSEPVLKGVKLHYT,1248,25,0.098158,0.008289,0.0,0

In [21]:
new_df.to_csv('data/processed/AllEpitopeFeatures_accounting_for_UK_and_SA_mutations.csv')